builds:
  - id: fuffa
    binary: fuffa
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    asmflags:
      - all=-trimpath={{.Env.PWD}}
    gcflags:
      - all=-trimpath={{.Env.PWD}}
    ldflags: |
      -s -w -X github.com/Mascol9/fuffa/pkg/ffuf.VERSION_APPENDIX= -extldflags '-static'
    goos:
      - linux
      - windows
      - freebsd
      - openbsd
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
